patterns:
  breakfast-card:
    width: 20em
    padding: 2em
  lunch-card:
    width: 20em
    padding: 2em
  dinner-card:
    width: 20em
    padding: 2em
  dessert-card:
    width: 20em
    padding: 2em
  waffle-card:
    width: 20em
    padding: 2em
  pancakes-card:
    width: 20em
    padding: 2em
  oatmeal-card:
    width: 20em
    padding: 2em
  omelette-card:
    width: 20em
    padding: 2em
